---
version: "3"

services:
    application:
        image: sb-app
        networks:
            - springmysql-net
        ports:
            -"8082:8082"
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql
        networks:
            - springmysql-net
        environment:
            - MYSQL_ROOT_PASSWORD: root
            - MYSQL_DATABASE: test_db 
...
    